### ISSUE TITLE
Go through Setup notebook to clear the error calls

### ISSUE THREAD

**Issue by vdevauxchupin** [vdevauxchupin/ITS_LIVE_TOOL#15]
- [ ] Clear Baltoro from setup.py
- [ ] Get rid of OGGM imports (that includes salem)
- [ ] git+https to pip install the package with the repo's URL in the README file
- [ ] Try the index.ipynb notebook until it works ! (meaning solve what doesn't work there)

**Comment by e-marshall** [comment]
These are all addressed in https://github.com/vdevauxchupin/ITS_LIVE_TOOL/pull/18

**Comment by e-marshall** [comment]
closing, i think we're good on this ?

**Comment by vdevauxchupin** [comment]
Yes !
