### ISSUE TITLE
Correct json path in interactive.py

### ISSUE THREAD

**Issue by vdevauxchupin** [vdevauxchupin/ITS_LIVE_TOOL#31]
Path to json in interactive.py (line 81) is hard-coded with the utah mesowest path. Needs to be changed in order to have roadmap.ipynb working.

**Comment by e-marshall** [comment]
shoot forgot about this -- not sure the best way to fix this other than having a note that the itslive catalog geojson file needs to be downloaded and then include an argument to pass its path when creating the widget? 
I just tried to pass a url to the where the file is in the gh repo and it didn't work, I'll try to see if i can fix it

**Comment by vdevauxchupin** [comment]
In my instance I just wrote the path as: "nbs/catalog_v02.json" in 'interactive.py', it seemed to work.

**Comment by e-marshall** [comment]
i just updated it to be a url so that users don't need to download the json file, will push in a minute

**Comment by e-marshall** [comment]
addressed in https://github.com/vdevauxchupin/ITS_LIVE_TOOL/pull/33
