### ISSUE TITLE
Change proj_cube to int(proj_cube)

### ISSUE THREAD

**Issue by vdevauxchupin** [vdevauxchupin/ITS_LIVE_TOOL#7]
proj_cube = store.attrs['projection']

needs to change to: proj_cube = int(store.attrs['projection'])

The string format can give errors in pyproj while the int format seems to be more stable.

**Comment by e-marshall** [comment]
this is fixed in https://github.com/vdevauxchupin/ITS_LIVE_TOOL/pull/11
