### ISSUE TITLE
Add GPU acceleration for the inversion

### ISSUE THREAD

**Issue by vdevauxchupin** [vdevauxchupin/ITS_LIVE_TOOL#8]
For small glaciers, if the GPU has enough RAM, GPU can be used to reduce computation time by up to 40% (approximate benchmark on 3 glaciers).

**Comment by vdevauxchupin** [comment]
Has been implemented, choice left to user to decide if run on CPU or GPU

**Comment by e-marshall** [comment]
code for this is added in invert.ipynb/invert.py in https://github.com/vdevauxchupin/ITS_LIVE_TOOL/pull/11
